### ISSUE TITLE
v1.1.0 doesnt have llama2 lora weights

### ISSUE THREAD

**Issue by vsingan** [WGLab/PhenoGPT#8]
Per the readme, LORA weights for LLama2 is available in github release v1.1.0. However the branch doesnt have the weights for the model.

**Comment by kaichop** [comment]
It is packaged in the release https://github.com/WGLab/PhenoGPT/releases/tag/v1.1.0

**Comment by vsingan** [comment]
Thanks !

**Comment by vsingan** [comment]
Thanks
